apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-deployment
  labels:
    app: counter
    version: consul
spec:
  replicas: 2
  selector:
    matchLabels:
      app: counter
      version: consul
  template:
    metadata:
      labels:
        app: counter
        version: consul
    spec:
      containers:
        - name: counter
          image: b4fun/counter:2018070201
          ports:
            - containerPort: 8081
