apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave-deployment
  labels:
    app: redis
    role: slave
    version: redis-cluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: slave
      version: redis-cluster
  template:
    metadata:
      labels:
        app: redis
        role: slave
        version: redis-cluster
    spec:
      containers:
        - name: master
          image: b4fun/counter-redis-slave:2018062202
          ports:
            - containerPort: 6379
