apiVersion: v1
kind: Service
metadata:
  name: redis-slave-service
  labels:
    app: redis
    role: slave
    version: redis-cluster
spec:
  selector:
    app: redis
    role: slave
    version: redis-cluster
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
