apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master-deployment
  labels:
    app: redis
    role: master
    version: redis-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
      version: redis-cluster
  template:
    metadata:
      labels:
        app: redis
        role: master
        version: redis-cluster
    spec:
      containers:
        - name: master
          image: redis:4-alpine
          ports:
            - containerPort: 6379
