apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
    version: basic
spec:
  selector:
    app: redis
    version: basic
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
